export const SCTS_TRANSLATE = 'SCTS_TRANSLATE';
export const SCTS_AUDIO = 'SCTS_AUDIO';
export const SCTS_DETECT = 'SCTS_DETECT';
/** chrome.i18n.detectLanguage — must run in service worker; not available in content scripts. */
export const SCTS_I18N_DETECT_LANGUAGE = 'SCTS_I18N_DETECT_LANGUAGE';
export const SCTS_CONTEXT_MENUS_CLICKED = 'SCTS_CONTEXT_MENUS_CLICKED';
export const SCTS_TRANSLATE_COMMAND_KEY_PRESSED = 'SCTS_TRANSLATE_COMMAND_KEY_PRESSED';
export const SCTS_AUDIO_COMMAND_KEY_PRESSED = 'SCTS_AUDIO_COMMAND_KEY_PRESSED';
export const SCTS_CALL_OUT_COMMAND_KEY_PRESSED = 'SCTS_CALL_OUT_COMMAND_KEY_PRESSED';
export const SCTS_CLOSE_COMMAND_KEY_PRESSED = 'SCTS_CLOSE_COMMAND_KEY_PRESSED';
export const SCTS_TRANSLATE_CURRENT_PAGE = 'SCTS_TRANSLATE_CURRENT_PAGE;'
export const SCTS_SWITCH_WT_DISPLAY_MODE = 'SCTS_SWITCH_WT_DISPLAY_MODE';
export const SCTS_IS_COLLECTED = 'SCTS_IS_COLLECTED';
export const SCTS_ADD_TO_COLLECTION = 'SCTS_ADD_TO_COLLECTION';
export const SCTS_REMOVE_FROM_COLLECTION = 'SCTS_REMOVE_FROM_COLLECTION';
export const SCTS_TOGGLE_PAGE_TRANSLATION_STATE = 'SCTS_TOGGLE_PAGE_TRANSLATION_STATE';